CREATE TABLE IF NOT EXISTS marca_files (
  id SERIAL PRIMARY KEY,
  marca_id UUID NOT NULL REFERENCES marcas(id) ON DELETE CASCADE,
  filename VARCHAR(255) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  size INTEGER NOT NULL,
  uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 